##########################################
###### Use este arquivo no perfil #######
##########################################

# Ativar repositório multilib (apenas para x86_64)
multilib="true"

# Gerenciador de exibição
displaymanager="lightdm"

# Definir para true para ativar login automático no livecd
autologin="true"

# Drivers mhwd não livres
nonfree_mhwd="true"

# Usar pacotes extras definidos no pkglist para ativar um perfil completo
extra="false"
# Para ativar, mude para: extra="true"

# Nome do arquivo ISO gerado
label="BigLinux.iso"

####################### Instalação #######################

# Carregador de inicialização EFI; deixe como padrão ou configure para "grub"
# efi_boot_loader="grub"

# Configurar o Calamares para instalação via netinstall
netinstall="false"

# Configurar o Calamares para usar chrootcfg em vez de unpackfs
chrootcfg="false"

# Usar geoip para localização automática
geoip="true"

# Configurar snaps estritos; deixe vazio ou defina snaps específicos
# strict_snaps="core core18 gnome-3-28-1804 gtk-common-themes snap-store"

# Configurar snaps clássicos; exemplo: classic_snaps="code"
# classic_snaps=""

# Canal de distribuição dos snaps; opções: stable, candidate, beta, edge
snap_channel="stable"

# Serviços para ativar durante a instalação
enable_systemd=('bluetooth' 'cronie' 'ModemManager' 'NetworkManager' 'cups' 'fstrim.timer' 'pkgfile-update.timer' 'vboxservice' 'ufw' 'avahi-daemon' 'smb' 'cups-browsed')

# Nome do grupo de trabalho Samba, se usado
# smb_workgroup="WORKGROUP"

###################### LiveCD ######################

# Nome do host no livecd
hostname="biglinux"

# Nome de usuário padrão no livecd
username="biglinux"

# Senha padrão no livecd
password="biglinux"

# Shell padrão no livecd
login_shell="/bin/bash"

# Grupos adicionais para o usuário live
addgroups="lp,network,power,wheel,sambashare,audio"

# Serviços para desativar no livecd
disable_systemd_live=('mirrors-live' 'pacman-init' 'ufw' 'fstrim.timer' 'big-btrfs-balance' 'auto-unlock-pacman')

# Argumentos personalizados para inicialização
custom_boot_args=('splash')
