name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'src'

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso

      - name: Verify structure
        run: |
          echo "Estrutura do repositório:"
          ls -lR src/
          echo "Procurando por perfis..."
          find src/ -type d -name "usr"

      - name: Build ISO
        run: |
          mkdir -p ./work ./out
          # Substitua pelo caminho CORRETO onde estão seus perfis
          mkarchiso -v -w ./work -o ./out ./src/usr/releng/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-iso
          path: ./out/*.iso
