name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso git

      - name: Build ISO
        run: |
          # Criar diretórios de trabalho
          mkdir -p ./work ./out

          # Verificar perfis disponíveis
          echo "Perfis disponíveis em usr/:"
          ls -l usr/

          # Construir ISO (substitua 'releng' pelo perfil desejado)
          mkarchiso -v -w ./work -o ./out ./usr/releng/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-iso
          path: ./out/*.iso
